## A PAIR OF FUNCTIONS THA CACHE THE INVERSE OF A MATRIX.


## FIRST FUNCTION
## makeCacheMatrix: Creates a special "matrix" object that can cache its inverse.

makeCacheMatrix <- function(x = matrix()) {
	## initialize the inverse matrix
    	invMatrix <- NULL
    
    		## set the matrix
    		set <- function(y) {
			x <<- y
			invMatrix <<- NULL
		}
    
    		## return the matrix
    		get <- function() {
      		x
    		}
    
    		## set the inverse matrix 
    		setInvMatrix <- function(invM){
      		invMatrix <<- invM
    		} 
    
    		## return the inverse matrix
    		getInvMatrix <- function(){
      		invMatrix
		}
    
    	## a list containing all the functions
    	list(set = set, get = get, setInvMatrix = setInvMatrix, getInvMatrix = getInvMatrix )
}


## SECOND FUNCTION
## cacheSolve: Computes the inverse of the special "matrix" returned by makeCacheMatrix above.
## If the inverse has already been calculated (and the matrix has not changed),
## then the cachesolve should retrieve the inverse from the cache.
## Write a short comment describing this function

cacheSolve <- function(x, ...) {
	## get the available inverse of the original matrix generated by makeCacheMatrix
    	invM <- x$getInvMatrix()
    
    	## checking if the inverse had already been calculated
    	if (!is.null(invM)){
        	message("getting cached data")
            return(invM)
    	}
    
    	## else part, if inverse matrix is null or matrix change, calculates the inverse as 
    	data <- x$get()
    	invM <- solve(data, ...)
    
    	## cache the inverse matrix value
    	x$setInvMatrix(invM)
    
    	## return the inverse matrix of 'x'
    	return(invM)
}